document.addEventListener('DOMContentLoaded', () => {
    // 1. Fetch the JSON data generated by your GitHub Action
    fetch('data.json')
        .then(response => {
            if (!response.ok) {
                throw new Error('Data file not found. Has the GitHub Action run yet?');
            }
            return response.json();
        })
        .then(data => {
            // Update League Title
            document.getElementById('league-name').innerText = data.league.name;
            
            const standings = data.standings.results;
            
            // Render the Top 3 Podium Cards
            renderPodium(standings.slice(0, 3));
            
            // Render the full table (including top 3 for completeness)
            renderTable(standings);
        })
        .catch(error => {
            console.error('Error fetching data:', error);
            document.getElementById('league-name').innerText = "Awaiting First Data Sync";
            document.getElementById('league-table-body').innerHTML = `
                <tr>
                    <td colspan="4" style="text-align: center; padding: 3rem; color: #6b7280;">
                        No data found. Ensure your GitHub Action has completed successfully.
                    </td>
                </tr>
            `;
        });
});

function renderPodium(topManagers) {
    const podiumContainer = document.getElementById('podium-container');
    
    // Only show podium if we actually have data
    if (topManagers.length === 0) return;
    podiumContainer.style.display = 'grid';

    let podiumHTML = '';

    topManagers.forEach(manager => {
        // Create the card structure for the top 3
        podiumHTML += `
            <div class="manager-card rank-${manager.rank}">
                <div class="card-rank">${manager.rank}</div>
                <div class="card-content">
                    <div class="card-team-name">${manager.entry_name}</div>
                    <div class="card-manager">${manager.player_name}</div>
                    
                    <div class="card-stats">
                        <div class="stat-group">
                            <span class="stat-label">GW Pts</span>
                            <span class="stat-value">${manager.event_total}</span>
                        </div>
                        <div class="stat-group">
                            <span class="stat-label">Total</span>
                            <span class="stat-value" style="color: var(--fpl-purple);">${manager.total}</span>
                        </div>
                    </div>
                </div>
            </div>
        `;
    });

    podiumContainer.innerHTML = podiumHTML;
}

function renderTable(standings) {
    const tbody = document.getElementById('league-table-body');
    let tableHTML = '';

    standings.forEach(manager => {
        // Determine Rank Movement Arrow
        let arrow = '<span class="arrow-flat">—</span>';
        if (manager.rank < manager.last_rank) {
            arrow = '<span class="arrow-up">▲</span>';
        } else if (manager.rank > manager.last_rank) {
            arrow = '<span class="arrow-down">▼</span>';
        }

        tableHTML += `
            <tr>
                <td>
                    <div class="rank-movement">
                        <span>${manager.rank}</span>
                        ${arrow}
                    </div>
                </td>
                <td>
                    <div class="team-info">
                        <span class="team-name">${manager.entry_name}</span>
                        <span class="manager-name">${manager.player_name}</span>
                    </div>
                </td>
                <td class="center-col">
                    <span class="pts-gw">${manager.event_total}</span>
                </td>
                <td class="center-col">
                    <span class="pts-total">${manager.total}</span>
                </td>
            </tr>
        `;
    });

    tbody.innerHTML = tableHTML;
}
